### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by DonaldBatryn** [DonaldBatryn/Job-Harmony#63]
maybe lighten the color of the nav

**Comment by DonaldBatryn** [comment]
far right dropdown menu, can we make it close when we click away from it or are off for a certain amount of time?

**Comment by dmhernandez2525** [comment]
- [ ]

**Comment by dmhernandez2525** [comment]
- [ ] d

**Comment by dmhernandez2525** [comment]
- [ ] ss

**Comment by hugginsc10** [comment]
chas will do

**Comment by hugginsc10** [comment]
also add fixed navbar on splash

**Comment by hugginsc10** [comment]
- [x] nav color
- [x] far right drop down closes on click or after 3 seconds
